spring:
  application:
    name: service-user
  cloud:
    consul:
      host: 10.11.1.107
      port: 8500
      discovery:
        tags: version=1.0,desc=用户服务
        health-check-path: ${server.servlet.context-path}/actuator/health
#  datasource:
#    username: root
#    password: ev@z9w5
#    url: jdbc:mysql://10.11.1.108:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.11.1.108:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
        username: root
        password: ev@z9w5
    sharding:
      tables:
        order:
          actual-data-nodes: m1.order_$->{1..2} #真实表节点
          key-generator:
            column: id
            type: SNOWFLAKE #解决分表之后解决主键冲突
          #配置分片策略
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_$->{id % 2 + 1} #分片的路由表达式
    props:
      sql:
        show: true
    enabled: true
mybatis:
  mapper-locations: classpath*:com/renshuo/cloud/**/*Mapper.xml
  type-aliases-package: com.renshuo.cloud.*.domain
  configuration:
    map-underscore-to-camel-case: true #驼峰
  mapperRefr`esher: #是否热部署
    enabled: true
    initialDelay: 30
logging:
  level:
    root: info

